name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches: [master, main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /CommonAssessmentTool
            sudo git pull
            sudo docker rm -f cs5500 
            sudo docker build -t cs5500:latest .
            sudo docker run -d -p 8000:8000 --name cs5500 cs5500:latest
