name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and run restart script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo git config --global --add safe.directory /CommonAssessmentTool
            cd /CommonAssessmentTool
            sudo git pull
            ls -l restart.sh
            sudo chmod +x restart.sh
            ./restart.sh
      - name: Post-deploy curl check
        run: |
          echo "Waiting for server to start..."
          sleep 10
          curl --fail http://ec2-3-141-168-148.us-east-2.compute.amazonaws.com:8000/health
