name: Docker CI Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  Docker-CI:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Checkout the repository

      - name: Install dependencies
        run: |
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint

      - name: Run Docker linting
        run: |
          hadolint --failure-threshold error Dockerfile

      - name: Run Docker Build
        run: |
          docker build -t myapp:latest .

      - name: Run Docker Container & Check Health
        run: |
          docker run -d -p 8000:8000 myapp:latest
          sleep 10
          wget --quiet --tries=1 --spider http://localhost:8000/health || (echo "Health check failed" && exit 1)

      - name: Print Success Message
        run: |
          echo "CI Pipeline completed successfully!"
          echo "========================"
          echo "✓ Code checked out"
          echo "✓ Python environment set up"
          echo "✓ Dependencies installed"
          echo "✓ Tests executed"
          echo "✓ Linting completed"
          echo "========================"
